In [ ]:
import pandas as pd 
import numpy as np 
import requests

import json
from io import StringIO

/Users/rehamrin/Desktop/ML HW/4th checkpoint/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

## Show_example

In [221]:
resp = requests.get('http://127.0.0.1:8000/api/models/show_example')

content = StringIO(resp.content.decode("utf-8"))
data = pd.read_csv(content).reset_index().drop(columns=['index'])
data.head()

,Unnamed: 0,Attendance,Performance3,Standard5,Poss,Standard4,Standard3,offside,crosses,fouls_drw,...,red,yellow,Standard8,result,GA,GF,date,team,venue,opponent
0,3720,22012,40.0,0.29,40.0,0.10,33.3,1,25,12,...,0,2,0,L,3,2,2020-02-15,Union Berlin,Home,Leverkusen
1,8712,2629,100.0,0.25,55.0,0.09,34.8,2,29,8,...,0,2,0,W,0,2,2024-01-06,Rayo Vallecano,Away,Huesca
2,9245,80902,100.0,0.33,62.0,0.07,21.4,3,22,11,...,0,3,0,W,0,1,2024-04-20,Manchester City,Neutral,Chelsea
3,2928,47000,100.0,0.50,44.0,0.19,37.5,1,13,13,...,0,3,0,W,0,3,2019-09-19,Arsenal,Away,Eint Frankfurt
4,4660,0,87.5,0.00,47.0,0.00,41.7,0,27,8,...,0,1,0,L,1,0,2020-12-23,Freiburg,Away,Stuttgart

## Fit

In [222]:
url = f'http://127.0.0.1:8000/api/models/fit?jsonfile={json.dumps({"model_id": "logistic_123", "hyperparameters": {}})}'

files = {
        'data': ('data/data_sample.csv', open('data/data_sample.csv', 'rb'), 'multipart/form-data')
}

resp = requests.post(url=url, files=files)
print(resp.json())

{'message': 'model logistic_123 is trained and saved'}

## Set_model

In [223]:
url = f'http://127.0.0.1:8000/api/models/set_model'
resp = requests.post(url=url, json={"id": "logistic_123"})
print(resp.json())

{'message': 'Model logistic_123 is loaded'}

## Show_models

In [224]:
url = f'http://127.0.0.1:8000/api/models/show_models'
resp = requests.get(url=url)
print(resp.json())

{'message': {'baseline_model': {'hyperparameters': {}}, 'logistic_123': {'hyperparameters': {}}}}

## Predict

In [225]:
url = f'http://127.0.0.1:8000/api/models/predict?jsonfile={json.dumps({"model_id": "logistic_123"})}'

files = {
        'data': ('data/data_sample.csv', open('data_sample_predict.csv', 'rb'), 'multipart/form-data')
}

resp = requests.post(url=url, files=files)
content = StringIO(resp.content.decode("utf-8"))
data = pd.read_csv(content).reset_index().drop(columns=['index'])
data.head()

,Attendance,Performance3,Standard5,Poss,Standard4,Standard3,offside,crosses,fouls_drw,fouls_com,...,red,yellow,Standard8,GA,GF,date,team,venue,opponent,preds
0,52962,62.5,0.00,48.0,0.00,28.6,7,25,14,15,...,0,3,0,3,0,2017-09-20,Hamburger SV,Home,Dortmund,0
1,75000,33.3,0.50,59.0,0.06,11.1,4,17,11,9,...,0,1,1,2,2,2017-09-22,Bayern Munich,Home,Wolfsburg,1
2,30150,66.7,0.00,56.0,0.00,12.5,2,27,17,16,...,0,2,0,2,0,2017-09-23,Schalke 04,Away,Hoffenheim,0
3,53053,66.7,0.83,42.0,0.42,50.0,0,16,11,11,...,0,0,0,1,5,2017-10-21,Leverkusen,Away,Gladbach,0
4,5612,0.0,0.00,0.0,0.00,0.0,0,0,0,0,...,0,2,0,0,1,2017-10-25,Metz,Home,Red Star,1